### ISSUE TITLE
[DOC-265] [DOC-231] Complete Whitelabel support

### ISSUE THREAD

**Issue by ElTimuro** [documenso/backlog#13]
* Documenso should support full white-label use cases
* Signing Experience, User Logins, and Admin Logins should be branded as desired
* While this will be a core part of the project, full technical whitelabel (custom-domain without any documenso branding) out of the box will likely be an enterprise-licensed feature

<sub>From [SyncLinear.com](https://synclinear.com) | [DOC-231](https://linear.app/documenso/issue/DOC-231/complete-whitelabel-support)</sub>

<sub>From [SyncLinear.com](https://synclinear.com) | [DOC-231](https://linear.app/documenso/issue/DOC-231/complete-whitelabel-support)</sub>

<sub>From [SyncLinear.com](https://synclinear.com) | [DOC-231](https://linear.app/documenso/issue/DOC-231/complete-whitelabel-support)</sub>

**Comment by Mythie** [comment]
As a first cut I'd consider this done since we now support the following:

- Setting your company logo and information on the documenso sent emails
- Adding custom css and css variables when using the embedding with platform features enabled.
- Changing the language of a document or team which modifies all emails and communications sent.
